name: React CI

on:
  pull_request:
    branches: ["**"]  # runs on every PR to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # adjust as per your project

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: CI='' npm run build

      - name: Run tests
        run: npm test
