name: React CI

on:
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: CI='' npm run build

      - name: Debug react-router-dom install
        run: |
          echo "Listing react-router-dom:"
          ls -la node_modules/react-router-dom || echo "❌ Not found!"
          npm ls react-router-dom || echo "❌ Not found in tree!"
